### ISSUE TITLE
Proxy is not defined

### ISSUE THREAD

**Issue by Scrum** [BohdanTkachenko/eslint-plugin-require-path-exists#24]
Hi, i have problem. [see more details](https://travis-ci.org/post-org/post-config/builds/227902911?utm_source=github_status&utm_medium=notification)

Node: 4, 5
OS: window 10

```bash
Proxy is not defined
ReferenceError: Proxy is not defined
    at Object.<anonymous> (/mnt/d/sand-box/git/post-config/node_modules/fs-plus/lib/fs-plus.js:708:24)
    at Object.<anonymous> (/mnt/d/sand-box/git/post-config/node_modules/fs-plus/lib/fs-plus.js:718:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/d/sand-box/git/post-config/node_modules/eslint-plugin-require-path-exists/lib/exists.js:10:15)
```

**Comment by BohdanTkachenko** [comment]
Caused by https://github.com/atom/fs-plus/issues/38
Will try to update fs-plus package version, maybe it will help

**Comment by Scrum** [comment]
if downgrade to 2.8 it work. i\`m use `eslint-plugin-require-path-exists@1.1.5` this works for me.

**Comment by alundiak** [comment]
My config:
Node 4.4.0, eslint 4.3.0.

```
eslint-plugin-require-path-exists@1.1.7 node_modules\eslint-plugin-require-path-exists
├── builtin-modules@1.1.1
├── resolve@1.4.0 (path-parse@1.0.5)
└── fs-plus@3.0.1 (async@1.5.2, underscore-plus@1.6.6, mkdirp@0.5.1, rimraf@2.6.1)
```

And I have:

```
Warning: Failed to load plugin require-path-exists: Proxy is not defined Use --force to continue.
```

Btw, I downgraded manually to fs-plus@2.8.0, but didn't help, the same error.

**Is this the same bug?**


PS. When I install 
```
npm install --save-dev eslint-plugin-require-path-exists@1.1.5
eslint-plugin-require-path-exists@1.1.5 node_modules\eslint-plugin-require-path-exists
├── builtin-modules@1.1.1
├── resolve@1.4.0 (path-parse@1.0.5)
└── fs-plus@2.10.1 (async@1.5.2, underscore-plus@1.6.6, mkdirp@0.5.1, rimraf@2.6.1)
```

I have then `Warning: Cannot read property 'recommended' of undefined`.
Setup rules manually (with no `extends`) helps.
